/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: eaaa24e833f12968948eab086451b533)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/pnl-api.app");
	}
	interface Env {
		DB: D1Database;
		ENVIRONMENT: "development";
		SENTRY_RELEASE: "unknown";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SENTRY_RELEASE">> {}
}
