// Generated by Wrangler by running `wrangler types`
// Run `pnpm -F pnl-api fix:workers-types` to regenerate after changing wrangler.jsonc bindings
interface Env {
	DB: D1Database
	ENVIRONMENT: string
	SENTRY_RELEASE: string
}
