/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1960bfa8a6dd3f73e86159ccb4aa6ee0)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "development";
	SENTRY_RELEASE: "unknown";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/pnl-api.app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SENTRY_RELEASE">> {}
}
