/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 281353963c7e7aff230e865d34bbce67)
interface __BaseEnv_Env {
	DB: D1Database;
	ENVIRONMENT: "development";
	SENTRY_RELEASE: "unknown";
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").PnLMcp>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PnLMcp";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SENTRY_RELEASE">> {}
}
