/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ace789598a8561a68dddd21498ee3a29)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PnLMcp";
	}
	interface Env {
		DB: D1Database;
		ENVIRONMENT: "development";
		SENTRY_RELEASE: "unknown";
		MCP_OBJECT: DurableObjectNamespace<import("./src/index").PnLMcp>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "SENTRY_RELEASE">> {}
}
